import neostandard from 'neostandard'

export default [
  // Vendored byte-identical from repository/active/base; lint it there.
  { ignores: ['cli/check-lockfile-age.mjs'] },
  // Build output, and openapi-typescript output regenerated by gen:api.
  { ignores: ['out/', 'release/', 'src/renderer/api/generated-types.ts'] },
  ...neostandard({ ts: true }),
  {
    // Project convention is snake_case for variables and functions.
    rules: { camelcase: 'off' }
  }
]
