/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tracks (paginated, filterable, sortable). */
        get: {
            parameters: {
                query?: {
                    /** @description Pagination offset. Default 0. */
                    offset?: components["parameters"]["Offset"];
                    /** @description Maximum results per page. Default 100, max 500. */
                    limit?: components["parameters"]["Limit"];
                    /** @description Filter by one or more library addresses. */
                    library_addresses?: string[];
                    /** @description Filter by tag labels. All supplied tags must match (AND semantics). */
                    tags?: string[];
                    /** @description Full-text search across title, artist, album, remixer. */
                    query?: string;
                    /** @description Randomize result order (overrides sort). */
                    shuffle?: boolean;
                    /** @description Sort field. Whitelisted to prevent injection. */
                    sort?: "title" | "artist" | "album" | "bpm" | "duration" | "added_at";
                    order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackList"];
                    };
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Adopt an existing track by content CID.
         * @description Adds a track that already exists in the content network (known by
         *     CID) to the requestor's own library. For URL ingest use
         *     `POST /import/url`; for file upload use `POST /import/file`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content_cid: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id (sha256 of the AcoustID fingerprint, lowercase hex). */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a track from the requestor's own library. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Track id (sha256 of the AcoustID fingerprint, lowercase hex). */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags with occurrence counts. */
        get: {
            parameters: {
                query?: {
                    /** @description Optional filter by library addresses. */
                    library_addresses?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagCount"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /** Attach a tag to a track in the requestor's own library. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        track_id: string;
                        tag: string;
                    };
                };
            };
            responses: {
                /** @description OK. Returns the updated track. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        /** Detach a tag from a track in the requestor's own library. */
        delete: {
            parameters: {
                query: {
                    track_id: string;
                    tag: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. Returns the updated track. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all locally-known libraries.
         * @description Union of libraries linked from the requestor's own library and
         *     libraries cached from peer discovery.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /** Link a library to the requestor's own library. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Full library address to link. */
                        library_address: string;
                        /** @description Optional display alias stored with the link entry. */
                        alias?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                400: components["responses"]["ValidationError"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        /**
         * Fetch metadata for a single library.
         * @description Connects to the library if not already connected, then returns
         *     full metadata. Progress is reported via the
         *     `library:replicate-progress` WebSocket event while the initial
         *     sync is in flight.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Unlink and drop a library.
         * @description Unlinks the library, drops the local replica, and unpins any
         *     content held uniquely by this library. There is no "unlink only"
         *     variant; unlink always implies drop.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unlinked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume replication for a library.
         * @description Returns immediately; progress is delivered via the
         *     `library:replicate-progress` WebSocket event.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted. Replication will resume asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause replication for a library. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted. Replication will pause asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/about": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        /**
         * Get the profile for a library.
         * @description Profile-only projection of the library. For full library metadata
         *     including replication status, use `GET /libraries/:address`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["About"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Update the profile for a library.
         * @description Returns 403 if the caller does not own the target library. Any
         *     subset of mutable fields may be supplied; omitted fields remain
         *     unchanged. Per protocol spec §2.6, `avatar` MUST be a
         *     content-addressed CID.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string | null;
                        bio?: string | null;
                        location?: string | null;
                        /** @description CID of an image blob. */
                        avatar?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["About"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated listen history.
         * @description Returns tracks enriched with listen counts and timestamps,
         *     ordered by most-recent-listen descending.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Pagination offset. Default 0. */
                    offset?: components["parameters"]["Offset"];
                    /** @description Maximum results per page. Default 100, max 500. */
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackList"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Record a listen event.
         * @description Server assigns the timestamp. Per protocol spec §2.7, listen
         *     entries are `{trackId, address, timestamp}`; the `address` is the
         *     library address the track was played from (may differ from the
         *     recording library if the listener is attributing a remote track).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        track_id: string;
                        /** @description Library address the track was played from. */
                        library_address: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListenCount"];
                    };
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List currently-connected libp2p peers.
         * @description Returns libp2p peers — not peer libraries. To fetch library
         *     metadata for a discovered peer, use `GET /libraries/:address`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Peer"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node info, bandwidth counters, and storage stats.
         * @description Read-only node-info envelope. Named `settings` for continuity with
         *     the task plan; there are no mutable server settings over HTTP.
         *     The chrome extension uses this only as a `peer_id` health check.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the node's identity keypair.
         * @description Returns the libp2p marshaled keypair in hex form. Both fields are
         *     the libp2p proto-encoded marshal (includes the key-type header).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdentityExport"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a keypair or generate a new one.
         * @description If `private_key` is omitted, generates a new keypair. If supplied,
         *     must be the libp2p marshaled form (hex). Restarts the node's
         *     identity; existing libraries on disk are orphaned until the
         *     matching private key is imported.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Hex-encoded libp2p marshaled private key. */
                        private_key?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description sha256 of the public key. */
                            id: string;
                            public_key: string;
                            own_library_address: string;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest one or more audio files via multipart upload.
         * @description Files are buffered to a temp directory and fed to the protocol-v1
         *     ingest pipeline via `import_blob(path)`. Returns an `import_id`
         *     immediately; progress is delivered via `import:*` WebSocket
         *     events.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        files: string[];
                    };
                };
            };
            responses: {
                /** @description Accepted. Ingest started asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAck"];
                    };
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a track from a resolver URL.
         * @description Resolves the URL via the resolver plugin, downloads, and feeds the
         *     result to the protocol-v1 ingest pipeline.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description Accepted. Ingest started asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAck"];
                    };
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description CID of the audio blob (`content.hash`). Accepts any valid
                 *     CID string: CIDv1, as written under the spec §5.5.1 import
                 *     profile, or legacy CIDv0 (`Qm...`).
                 */
                cid: string;
            };
            cookie?: never;
        };
        /**
         * Stream audio content by CID.
         * @description MIME type is detected from the first 4100 bytes via file-type.
         *     Supports RFC 7233 Range requests (206 Partial Content). No
         *     side-effects — pinning is handled when a track is adopted into
         *     the requestor's own library, not when its audio is streamed.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional byte range, e.g. `bytes=0-1023`. */
                    Range?: string;
                };
                path: {
                    /**
                     * @description CID of the audio blob (`content.hash`). Accepts any valid
                     *     CID string: CIDv1, as written under the spec §5.5.1 import
                     *     profile, or legacy CIDv0 (`Qm...`).
                     */
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full content stream. */
                200: {
                    headers: {
                        "Content-Type"?: string;
                        "Content-Length"?: number;
                        "Accept-Ranges"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Partial content stream. */
                206: {
                    headers: {
                        "Content-Type"?: string;
                        "Content-Length"?: number;
                        "Content-Range"?: string;
                        "Accept-Ranges"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Check local availability of an audio blob.
         * @description Returns 200 if the CID is present in the local content store,
         *     404 otherwise. Side-effect-free; use this for UI pre-checks
         *     before committing to a streaming GET.
         */
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description CID of the audio blob (`content.hash`). Accepts any valid
                     *     CID string: CIDv1, as written under the spec §5.5.1 import
                     *     profile, or legacy CIDv0 (`Qm...`).
                     */
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Locally available. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not in the local content store. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch?: never;
        trace?: never;
    };
    "/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview track metadata for a URL without downloading. */
        get: {
            parameters: {
                query: {
                    url: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResolverEntry"];
                    };
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Structured error envelope. All non-2xx responses use this shape. */
        Error: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "NOT_FOUND" | "CONFLICT" | "UNAUTHORIZED" | "FORBIDDEN" | "INTERNAL_ERROR";
                /** @description Human-readable message suitable for UI display. */
                message: string;
                /** @description Optional structured per-field errors (validation). */
                details?: {
                    field?: string;
                    message?: string;
                }[];
            };
        };
        /**
         * @description Paginated list wrapper. `total` is the unpaginated match count
         *     (for UI page counts); `items.length` reflects the current page.
         */
        TrackList: {
            items: components["schemas"]["Track"][];
            total: number;
        };
        /**
         * @description API-layer Track shape. Enumerated fields are flattened from the
         *     protocol-layer dag-cbor content payload (spec §2.4.1); the raw
         *     content object is intentionally NOT passed through.
         */
        Track: {
            /** @description sha256 of the AcoustID fingerprint (lowercase hex). */
            id: string;
            /** @description Base58btc CID of the dag-cbor content payload. */
            content_cid: string;
            /** @description CID of the tag-stripped audio blob (from `content.hash`). */
            audio_cid: string;
            /** @description Size of the audio blob (from `content.size`). */
            audio_size_bytes: number;
            title?: string | null;
            artist?: string | null;
            artists?: string[];
            album?: string | null;
            album_artist?: string | null;
            remixer?: string | null;
            genre?: string[];
            bpm?: number | null;
            duration_seconds?: number | null;
            bitrate?: number | null;
            codec?: string | null;
            sample_rate?: number | null;
            lossless?: boolean | null;
            /** @description CIDs of album-art blobs. */
            artwork?: string[];
            /** @description External source pointers per protocol spec §2.4.2. */
            resolvers?: components["schemas"]["ResolverEntry"][];
            /** @description Library-scoped tag labels attached to this track. */
            tags: components["schemas"]["TrackTag"][];
            /** @description Total listens recorded for this track across all libraries. */
            listen_count: number;
            /** @description Unix milliseconds of each listen. May be omitted on list endpoints for payload weight. */
            listen_timestamps_ms?: number[];
            /** @description Whether the track exists in the requestor's own library. */
            have_track: boolean;
            /** @description First-seen timestamp (unix milliseconds) in the requestor's index. */
            added_at_ms?: number;
        };
        TrackTag: {
            /** @description Library address that applied the tag. */
            library_address: string;
            tag: string;
        };
        TagCount: {
            tag: string;
            /** @description Number of tracks carrying this tag in the filtered address set. */
            count: number;
        };
        /**
         * @description Library metadata. Flat API-layer shape — no protocol-level
         *     passthrough, no spread-source merging. Replaces the legacy
         *     `logs.get` `extend(about, peerEntry, entry, myEntry, {...})`
         *     pattern with an enumerated contract.
         */
        Library: {
            /** @description sha256 of the library address. */
            id: string;
            address: string;
            name?: string | null;
            bio?: string | null;
            location?: string | null;
            /** @description CID of the library's avatar image (protocol spec §2.6). */
            avatar?: string | null;
            /**
             * @description Display alias from the link entry in the requestor's library.
             *     Null when not linked or when no alias was provided.
             */
            alias?: string | null;
            track_count: number;
            linked_library_count: number;
            /** @description Oplog length (count of live entries). */
            length: number;
            replication_status: components["schemas"]["ReplicationStatus"];
            is_replicating: boolean;
            is_loading_index: boolean;
            is_processing_index: boolean;
            /** @description Whether the requestor's own library links to this one. */
            is_linked: boolean;
            /** @description Whether this library IS the requestor's own library. */
            is_own: boolean;
            /** @description libp2p peer ids currently subscribed to this library's pubsub topic. */
            peer_ids: string[];
        };
        /**
         * @description Normalized replication progress. Same shape as the
         *     `library:replicate-progress` WebSocket event payload.
         */
        ReplicationStatus: {
            /** @description Count of entries synced so far. */
            progress: number;
            /** @description Total entries expected in the current sync window. */
            total: number;
        };
        /** @description Profile-only projection of a library. */
        About: {
            library_address: string;
            name?: string | null;
            bio?: string | null;
            location?: string | null;
            avatar?: string | null;
        };
        ListenCount: {
            track_id: string;
            count: number;
            timestamps_ms?: number[];
        };
        Peer: {
            peer_id: string;
            multiaddrs: string[];
            /** @description Library addresses advertised by this peer. */
            library_addresses?: string[];
            /** @description Unix milliseconds when the peer connection was established. */
            connected_at_ms?: number;
        };
        /**
         * @description Node info. `peer_id` is the only guaranteed field; everything
         *     else is optional and may be omitted when unavailable.
         */
        Settings: {
            /** @description libp2p peer id of the node. */
            peer_id: string;
            /** @description libp2p multiaddrs the node is listening on. */
            addresses?: string[];
            /** @description record-node build version. */
            version?: string;
            /**
             * @description Bandwidth counters. Values are decimal-encoded strings
             *     because the underlying counters are unbounded integers.
             */
            bandwidth?: {
                total_in_bytes?: string;
                total_out_bytes?: string;
                rate_in_bytes_per_sec?: string;
                rate_out_bytes_per_sec?: string;
            };
            storage?: {
                used_bytes?: number;
                max_bytes?: number;
                object_count?: number;
            };
        };
        /**
         * @description Hex-encoded libp2p marshaled keypair. Both fields include the
         *     key-type header so `private_key` round-trips through
         *     `POST /identity/import`.
         */
        IdentityExport: {
            public_key: string;
            private_key: string;
        };
        ImportAck: {
            /**
             * Format: uuid
             * @description Identifier for tracking progress via `import:*` WebSocket events.
             */
            import_id: string;
            /** @description Number of files accepted (multipart only). */
            file_count?: number;
        };
        /**
         * @description Canonical shape per protocol spec §2.4.2. `(extractor, id)` MUST
         *     uniquely identify an external source pointer. Streaming `url`
         *     fields MUST NOT be persisted (spec §2.4.2).
         */
        ResolverEntry: {
            extractor: string;
            id: string;
            fulltitle?: string;
            thumbnail?: string;
            artist?: string;
            alt_title?: string;
            upload_date?: string;
            webpage_url?: string;
            duration?: number;
        };
    };
    responses: {
        /** @description Request validation failed. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Caller is not authorized to perform this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation conflicts with existing state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unhandled exception. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Pagination offset. Default 0. */
        Offset: number;
        /** @description Maximum results per page. Default 100, max 500. */
        Limit: number;
        /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
        LibraryAddress: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
