/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tracks (paginated, filterable, sortable). */
        get: {
            parameters: {
                query?: {
                    /** @description Pagination offset. Default 0. */
                    offset?: components["parameters"]["Offset"];
                    /** @description Maximum results per page. Default 100, max 500. */
                    limit?: components["parameters"]["Limit"];
                    /** @description Filter by one or more library addresses. */
                    library_addresses?: string[];
                    /** @description Filter by tag labels. All supplied tags must match (AND semantics). */
                    tags?: string[];
                    /** @description Full-text search across title, artist, album, remixer. */
                    query?: string;
                    /** @description Randomize result order (overrides sort). */
                    shuffle?: boolean;
                    /** @description Sort field. Whitelisted to prevent injection. */
                    sort?: "title" | "artist" | "album" | "bpm" | "duration" | "added_at";
                    order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackList"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Adopt an existing track by content CID.
         * @description Adds a track that already exists in the content network (known by
         *     CID) to the target library (spec §6.4.3). Adopting into a library
         *     the identity does not own needs a capability granting
         *     `library.append_track`. For URL ingest use `POST /import/url`; for
         *     file upload use `POST /import/file`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content_cid: string;
                        library_address?: components["schemas"]["WriteTargetAddress"];
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id (sha256 of the AcoustID fingerprint, lowercase hex). */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a track from an own library.
         * @description Appends a DEL to the target library. No capability action
         *     authorises a DEL (spec §3.5.6), so the target must be an own
         *     library.
         */
        delete: {
            parameters: {
                query?: {
                    /**
                     * @description Target library of the write. Optional only when the identity has
                     *     exactly one active own recordstore library (spec §4.8.3).
                     */
                    library_address?: components["parameters"]["WriteTarget"];
                };
                header?: never;
                path: {
                    /** @description Track id (sha256 of the AcoustID fingerprint, lowercase hex). */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Correct a track's audio metadata.
         * @description Writes a new content object (spec §2.4.1) for the same audio, with
         *     `content.tags` changed as the request says, and appends a PUT of it
         *     under the same track id, which supersedes the current one (spec
         *     §4.4.2). The audio blob and its size, `audio`, `artwork`,
         *     `resolver`, and the envelope's labels (spec §2.4.3) are kept.
         *
         *     Each field of `tags` sets that tag, and `null` removes it.
         *     `acoustid_fingerprint` derives the track id, so a request that
         *     changes it fails with 400. A request that changes nothing appends
         *     nothing. Under a capability the write needs `library.append_track`
         *     (spec §3.5.6).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Track id (sha256 of the AcoustID fingerprint, lowercase hex). */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Tag names to new values, or `null` to remove the tag. */
                        tags: {
                            [key: string]: unknown;
                        };
                        library_address?: components["schemas"]["WriteTargetAddress"];
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description The track as the target library now holds it. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /**
                 * @description The target is retired, or the node does not hold the track's
                 *     current content payload, so it has nothing to correct.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        trace?: never;
    };
    "/tracks/{id}/rederive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id (sha256 of the AcoustID fingerprint, lowercase hex). */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute a track's decoded audio fields.
         * @description Audio re-derivation (spec §6.4.4). The node decodes the audio blob
         *     it holds for the track and recomputes `duration`,
         *     `numberOfSamples`, and `bitrate` (spec §6.3.2). When any differs
         *     from the stored value, it writes a new content object with only
         *     those fields changed and appends a PUT of it under the same track
         *     id, which supersedes the current one (spec §4.4.2). Everything
         *     else, including the envelope's labels, is kept. A track whose
         *     stored fields already match appends nothing, so the request is
         *     safe to repeat.
         *
         *     The values are computed by the node and never taken from the
         *     client. Under a capability the write needs `library.append_track`
         *     (spec §3.5.6).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Track id (sha256 of the AcoustID fingerprint, lowercase hex). */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        library_address?: components["schemas"]["WriteTargetAddress"];
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description The track as the target library now holds it. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /**
                 * @description The target is retired, or the node does not hold the track's
                 *     current content payload or its audio blob, or the blob decodes
                 *     to no samples.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/{cid}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description CID of the audio blob (`content.hash`), in any valid CID form.
                 *     The node records it in the canonical form of spec §4.8.2
                 *     (CIDv1, base32).
                 */
                cid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pin a track's audio blob.
         * @description Appends a `pin` PUT to the identity library (spec §4.8.2). Every
         *     device of the identity then fetches and keeps the blob whatever
         *     the replication policy (spec §4.6.2). Pinning a pinned blob is a
         *     no-op.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description CID of the audio blob (`content.hash`), in any valid CID form.
                     *     The node records it in the canonical form of spec §4.8.2
                     *     (CIDv1, base32).
                     */
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pinned. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Unpin a track's audio blob.
         * @description Appends a `pin` DEL to the identity library. The blob stays if an
         *     own library or a replication policy still holds it (spec §4.6.2).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description CID of the audio blob (`content.hash`), in any valid CID form.
                     *     The node records it in the canonical form of spec §4.8.2
                     *     (CIDv1, base32).
                     */
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unpinned. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags with occurrence counts. */
        get: {
            parameters: {
                query?: {
                    /** @description Optional filter by library addresses. */
                    library_addresses?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagCount"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Attach a tag to a track in the target library.
         * @description Under a capability, needs `library.append_tag` or
         *     `library.append_track` (spec §3.5.6).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        track_id: string;
                        tag: string;
                        library_address?: components["schemas"]["WriteTargetAddress"];
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description OK. Returns the updated track. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Detach a tag from a track in the target library.
         * @description Under a capability, needs `library.append_track`:
         *     `library.append_tag` only adds tags (spec §3.5.6).
         */
        delete: {
            parameters: {
                query: {
                    track_id: string;
                    tag: string;
                    /**
                     * @description Target library of the write. Optional only when the identity has
                     *     exactly one active own recordstore library (spec §4.8.3).
                     */
                    library_address?: components["parameters"]["WriteTarget"];
                    /**
                     * @description Capability authorising the write (spec §3.5.9). Required when the
                     *     identity does not own the target; omitted otherwise.
                     */
                    capability_id?: components["parameters"]["WriteCapability"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. Returns the updated track. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all locally-known libraries.
         * @description Union of the identity's own libraries (spec §4.8.3), its linked
         *     libraries (spec §4.8.4), and libraries cached from peer
         *     discovery. Identity libraries are not listed; read the
         *     identity's own through `GET /identity/meta-log`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Link a library.
         * @description Appends a `link` PUT to the identity library (spec §4.8.4).
         *     Replication then starts under the library's replication policy,
         *     `full` unless configured. A link made before v1.1 defaults to
         *     `index_only` (spec §4.6.1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Full library address to link. */
                        library_address: string;
                        /** @description Optional display alias stored with the link record. */
                        alias?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        /**
         * Fetch metadata for a single library.
         * @description Connects to the library if not already connected, then returns
         *     full metadata. Progress is reported via the
         *     `library:replicate-progress` WebSocket event while the initial
         *     sync is in flight.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Unlink and drop a library.
         * @description Appends a `link` DEL to the identity library (spec §4.8.4), drops
         *     the local replica, and unpins any content held uniquely by this
         *     library, except pinned blobs (spec §4.6). There is no "unlink
         *     only" variant; unlink always implies drop. An own library cannot
         *     be unlinked (409); retire it with
         *     `DELETE /identity/libraries/{address}`.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unlinked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/replication-policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        /**
         * Get the node-local replication policy for a library.
         * @description Spec §4.6.1. For an own library the mode is always `full`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReplicationPolicy"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Set the node-local replication policy for a linked library.
         * @description Node-local configuration, not written to any log (spec §4.6.1).
         *     `filter` is required for `selective` and ignored otherwise. A
         *     filter the node cannot evaluate (unknown node type or malformed
         *     shape, spec §3.5.7) is refused with 400. An own library's policy
         *     cannot be changed (409). Connection state is changed through
         *     `/connect` and `/disconnect`, not here.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        mode: components["schemas"]["ReplicationMode"];
                        filter?: components["schemas"]["FilterSpec"];
                    };
                };
            };
            responses: {
                /** @description OK. Returns the stored policy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReplicationPolicy"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        /**
         * List every capability issued in a library.
         * @description All capability records in the library's log, with their status
         *     (spec §3.5.5, §3.5.10). Readable for any known library.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Issue a capability.
         * @description Appends a capability record (spec §3.5.5) to the library. The
         *     owner issues directly; any other identity cites, as
         *     `capability_id`, a capability granting
         *     `library.grant_capability` (spec §3.5.9). The node refuses with
         *     400 a capability holding an action, GranteeSpec, FilterSpec, or
         *     ConditionSpec type it does not recognise, since it could not
         *     verify writes under it. Capabilities exist only in recordstore
         *     libraries.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        grantee: components["schemas"]["GranteeSpec"];
                        actions: string[];
                        filter?: components["schemas"]["FilterSpec"];
                        conditions?: components["schemas"]["ConditionSpec"][];
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description Issued. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/capabilities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
                /** @description Capability id of the capability to revoke (spec §3.5.5). */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a capability.
         * @description Appends a revocation record (spec §3.5.10). The owner revokes any
         *     capability directly. Any other identity may revoke only a
         *     capability it issued, or one descending from a capability it
         *     issued, and passes as the `capability_id` query parameter a
         *     capability it holds. Revocation is not retroactive: entries the
         *     node had merged when it revoked stay valid, concurrent entries
         *     under the capability become inert, and later ones are rejected.
         */
        delete: {
            parameters: {
                query?: {
                    /**
                     * @description Capability authorising the write (spec §3.5.9). Required when the
                     *     identity does not own the target; omitted otherwise.
                     */
                    capability_id?: components["parameters"]["WriteCapability"];
                };
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                    /** @description Capability id of the capability to revoke (spec §3.5.5). */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume replication for a library.
         * @description Returns immediately; progress is delivered via the
         *     `library:replicate-progress` WebSocket event.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted. Replication will resume asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause replication for a library. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted. Replication will pause asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{address}/about": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        /**
         * Get the profile for a library.
         * @description Profile-only projection of the library. For full library metadata
         *     including replication status, use `GET /libraries/:address`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["About"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Update the profile for a library.
         * @description Returns 403 unless the caller owns the target library or cites a
         *     capability granting `library.update_about` (spec §3.5.6). Any
         *     subset of mutable fields may be supplied; omitted fields remain
         *     unchanged. Per protocol spec §2.6, `avatar` MUST be a
         *     content-addressed CID.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string | null;
                        bio?: string | null;
                        location?: string | null;
                        /** @description CID of an image blob. */
                        avatar?: string | null;
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["About"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated listen history.
         * @description Returns tracks enriched with listen counts and timestamps,
         *     ordered by most-recent-listen descending.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Pagination offset. Default 0. */
                    offset?: components["parameters"]["Offset"];
                    /** @description Maximum results per page. Default 100, max 500. */
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Record a listen event.
         * @description Server assigns the timestamp. Per protocol spec §2.7, listen
         *     entries are `{trackId, address, timestamp}`; the `address` is the
         *     library address the track was played from (may differ from the
         *     recording library if the listener is attributing a remote track).
         *     The listen is written to the identity's listens library (spec
         *     §4.8.3); there is no write target.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        track_id: string;
                        /** @description Library address the track was played from. */
                        library_address: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListenCount"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List currently-connected libp2p peers.
         * @description Returns libp2p peers — not peer libraries. To fetch library
         *     metadata for a discovered peer, use `GET /libraries/:address`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Peer"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node info, bandwidth counters, and storage stats.
         * @description Read-only node-info envelope. Named `settings` for continuity with
         *     the task plan; there are no mutable server settings over HTTP.
         *     The chrome extension uses this only as a `peer_id` health check.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the node's identity.
         * @description Public identity facts for display. Clients read the public key
         *     here; `GET /identity/export` returns private key material and is
         *     for an explicit user export only (spec §8.5.7).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the node's identity keypair.
         * @description Returns the libp2p marshaled keypair in hex form. Both fields are
         *     the libp2p proto-encoded marshal (includes the key-type header).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdentityExport"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a keypair or generate a new one.
         * @description If `private_key` is omitted, generates a new keypair. If supplied,
         *     must be the libp2p marshaled form (hex). Restarts the node's
         *     identity; existing libraries on disk are orphaned until the
         *     matching private key is imported.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Hex-encoded libp2p marshaled private key. */
                        private_key?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description sha256 of the public key. */
                            id: string;
                            public_key: string;
                            /**
                             * @description The identity's default own recordstore library: its
                             *     only active one, or else the one with discriminator
                             *     `record`, record-node's v1.0 own library (spec
                             *     §3.6.1). `GET /identity/libraries` lists them all.
                             */
                            own_library_address: string;
                            /** @description Address of the identity library (spec §3.6.2). */
                            meta_log_address: string;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the identity's own libraries.
         * @description Every library the identity library records as owned (spec §4.8.3),
         *     active and retired, including the listens library.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Create an own recordstore library.
         * @description Derives the address from the identity key and the discriminator
         *     (spec §3.6.1), appends a `library` PUT to the identity library,
         *     and, when `about` is given, an About entry to the new library. If
         *     `discriminator` is omitted the node generates one. A discriminator
         *     the identity library already records, active or retired, is
         *     refused with 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        discriminator?: string;
                        about?: {
                            name?: string | null;
                            bio?: string | null;
                            location?: string | null;
                            avatar?: string | null;
                        };
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/libraries/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                address: components["parameters"]["LibraryAddress"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Retire an own library.
         * @description Appends a `library` DEL to the identity library (spec §4.8.3).
         *     Retirement is permanent. The library stays valid and replicable;
         *     the node refuses new writes to it. The identity's active listens library cannot be retired
         *     (409).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
                    address: components["parameters"]["LibraryAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retired. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List capabilities held by the identity.
         * @description Every capability, in any known library, whose grantee matches the
         *     identity's key (spec §3.5.5), with its status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/meta-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the identity library.
         * @description Records of the identity library (spec §4.8.2), newest first by
         *     `clock_time`. The library replicates across the identity's
         *     devices, so records may come from another device.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Pagination offset. Default 0. */
                    offset?: components["parameters"]["Offset"];
                    /** @description Maximum results per page. Default 100, max 500. */
                    limit?: components["parameters"]["Limit"];
                    /** @description Only records of this type. */
                    type?: "library" | "link" | "pin";
                    /** @description Only the current record of each `(type, key)` (spec §4.8.2). */
                    current_only?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetaLogPage"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest one or more audio files via multipart upload.
         * @description Files are buffered to a temp directory and fed to the protocol-v1
         *     ingest pipeline via `import_blob(path)`. Returns an `import_id`
         *     immediately; progress is delivered via `import:*` WebSocket
         *     events. The target and capability are checked before the import
         *     is accepted. A file with a degenerate fingerprint fails with
         *     `DEGENERATE_FINGERPRINT`, and one whose track id the target holds
         *     for audio of a different duration fails with `TRACK_ID_COLLISION`
         *     (spec §6.4.1), each as an `import:error` event.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        files: string[];
                        library_address?: components["schemas"]["WriteTargetAddress"];
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description Accepted. Ingest started asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAck"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a track from a resolver URL.
         * @description Resolves the URL via the resolver plugin, downloads, and feeds the
         *     result to the protocol-v1 ingest pipeline.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                        library_address?: components["schemas"]["WriteTargetAddress"];
                        capability_id?: components["schemas"]["WriteCapabilityId"];
                    };
                };
            };
            responses: {
                /** @description Accepted. Ingest started asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAck"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalError"];
                502: components["responses"]["ResolverFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description CID of the audio blob (`content.hash`). Accepts any valid
                 *     CID string: CIDv1, as written under the spec §5.5.1 import
                 *     profile, or legacy CIDv0 (`Qm...`).
                 */
                cid: string;
            };
            cookie?: never;
        };
        /**
         * Stream audio content by CID.
         * @description MIME type is detected from the first 4100 bytes via file-type.
         *     Supports RFC 7233 Range requests (206 Partial Content). No
         *     side-effects — pinning is handled when a track is adopted into
         *     the requestor's own library, not when its audio is streamed.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional byte range, e.g. `bytes=0-1023`. */
                    Range?: string;
                };
                path: {
                    /**
                     * @description CID of the audio blob (`content.hash`). Accepts any valid
                     *     CID string: CIDv1, as written under the spec §5.5.1 import
                     *     profile, or legacy CIDv0 (`Qm...`).
                     */
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full content stream. */
                200: {
                    headers: {
                        "Content-Type"?: string;
                        "Content-Length"?: number;
                        "Accept-Ranges"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Partial content stream. */
                206: {
                    headers: {
                        "Content-Type"?: string;
                        "Content-Length"?: number;
                        "Content-Range"?: string;
                        "Accept-Ranges"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Check local availability of an audio blob.
         * @description Returns 200 if the CID is present in the local content store,
         *     404 otherwise. Side-effect-free; use this for UI pre-checks
         *     before committing to a streaming GET.
         */
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description CID of the audio blob (`content.hash`). Accepts any valid
                     *     CID string: CIDv1, as written under the spec §5.5.1 import
                     *     profile, or legacy CIDv0 (`Qm...`).
                     */
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Locally available. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                /** @description Not in the local content store. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch?: never;
        trace?: never;
    };
    "/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview track metadata for a URL without downloading. */
        get: {
            parameters: {
                query: {
                    url: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResolverEntry"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
                502: components["responses"]["ResolverFailed"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Structured error envelope. All non-2xx responses use this shape. */
        Error: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "NOT_FOUND" | "CONFLICT" | "UNAUTHORIZED" | "FORBIDDEN" | "CAPABILITY_EXPIRED" | "CAPABILITY_REVOKED" | "TRACK_ID_COLLISION" | "DEGENERATE_FINGERPRINT" | "RESOLVER_FAILED" | "INTERNAL_ERROR";
                /** @description Human-readable message suitable for UI display. */
                message: string;
                /**
                 * @description With `RESOLVER_FAILED` only: the resolver's own error code,
                 *     e.g. `YTDLP_NOT_FOUND`, `YTDLP_FAILED`, `YTDLP_TIMEOUT`.
                 */
                resolver_code?: string;
                /** @description Optional structured per-field errors (validation). */
                details?: {
                    field?: string;
                    message?: string;
                }[];
            };
        };
        /**
         * @description Paginated list wrapper. `total` is the unpaginated match count
         *     (for UI page counts); `items.length` reflects the current page.
         */
        TrackList: {
            items: components["schemas"]["Track"][];
            total: number;
        };
        /**
         * @description API-layer Track shape. Enumerated fields are flattened from the
         *     protocol-layer dag-cbor content payload (spec §2.4.1); the raw
         *     content object is intentionally NOT passed through.
         */
        Track: {
            /** @description sha256 of the AcoustID fingerprint (lowercase hex). */
            id: string;
            /**
             * @description The libraries holding a live PUT of the track, among those the
             *     request covers: the `library_addresses` filter when given, else
             *     every library the node shows. A list folds a track several
             *     libraries hold into one item, so this says which they are.
             */
            library_addresses: string[];
            /** @description Base58btc CID of the dag-cbor content payload. */
            content_cid: string;
            /** @description CID of the tag-stripped audio blob (from `content.hash`). */
            audio_cid: string;
            /** @description Size of the audio blob (from `content.size`). */
            audio_size_bytes: number;
            title?: string | null;
            artist?: string | null;
            artists?: string[];
            album?: string | null;
            album_artist?: string | null;
            remixer?: string | null;
            genre?: string[];
            bpm?: number | null;
            duration_seconds?: number | null;
            bitrate?: number | null;
            codec?: string | null;
            sample_rate?: number | null;
            lossless?: boolean | null;
            /** @description CIDs of album-art blobs. */
            artwork?: string[];
            /** @description External source pointers per protocol spec §2.4.2. */
            resolvers?: components["schemas"]["ResolverEntry"][];
            /** @description Library-scoped tag labels attached to this track. */
            tags: components["schemas"]["TrackTag"][];
            /** @description Total listens recorded for this track across all libraries. */
            listen_count: number;
            /** @description Unix milliseconds of each listen. May be omitted on list endpoints for payload weight. */
            listen_timestamps_ms?: number[];
            /** @description Whether the track exists in any of the identity's own libraries. */
            have_track: boolean;
            /** @description Whether a current pin record holds `audio_cid` (spec §4.6.2). */
            is_pinned?: boolean;
            /** @description First-seen timestamp (unix milliseconds) in the requestor's index. */
            added_at_ms?: number;
        };
        TrackTag: {
            /** @description Library address that applied the tag. */
            library_address: string;
            tag: string;
        };
        TagCount: {
            tag: string;
            /** @description Number of tracks carrying this tag in the filtered address set. */
            count: number;
        };
        /**
         * @description Library metadata. Flat API-layer shape — no protocol-level
         *     passthrough, no spread-source merging. Replaces the legacy
         *     `logs.get` `extend(about, peerEntry, entry, myEntry, {...})`
         *     pattern with an enumerated contract.
         */
        Library: {
            /** @description sha256 of the library address. */
            id: string;
            address: string;
            /** @description Manifest type (spec §3.5.1), `recordstore` or `listens`. */
            library_type: string;
            name?: string | null;
            bio?: string | null;
            location?: string | null;
            /** @description CID of the library's avatar image (protocol spec §2.6). */
            avatar?: string | null;
            /**
             * @description Display alias from the identity's link to this library (spec
             *     §4.8.4). Null when not linked or when no alias was provided.
             */
            alias?: string | null;
            track_count: number;
            /**
             * @description Total size of the audio blobs of the library's live tracks
             *     (`content.size`), for storage estimates. A track whose content
             *     payload the node does not hold yet counts zero.
             */
            audio_size_bytes: number;
            linked_library_count: number;
            /** @description Oplog length (count of live entries). */
            length: number;
            /**
             * @description Current head entry hashes (spec §4.3), base58btc. Clients
             *     compare them to detect missed updates (spec §8.8.5).
             */
            heads: string[];
            replication_status: components["schemas"]["ReplicationStatus"];
            is_replicating: boolean;
            /**
             * @description Whether replication runs for this library, false while paused
             *     by `/disconnect` (spec §5.4.4). Paused is the only other state,
             *     so a boolean suffices. Matches `ReplicationPolicy.connected`.
             */
            connected: boolean;
            is_loading_index: boolean;
            is_processing_index: boolean;
            /** @description Whether the library is in the identity's link set (spec §4.8.4). */
            is_linked: boolean;
            /** @description Whether this is one of the identity's own libraries (spec §4.8.3), active or retired. */
            is_own: boolean;
            /** @description Whether this own library is retired (spec §4.8.3). Always false when `is_own` is false. */
            is_retired: boolean;
            /**
             * @description Ids of the active capabilities the identity holds in this
             *     library (spec §3.5.5). Non-empty marks a shared library.
             */
            held_capability_ids: string[];
            /** @description Replication mode (spec §4.6.1); null when neither own nor linked. */
            replication_mode?: components["schemas"]["ReplicationMode"] | null;
            /** @description libp2p peer ids currently subscribed to this library's pubsub topic. */
            peer_ids: string[];
        };
        /**
         * @description Target library of the write. Optional only when the identity has
         *     exactly one active own recordstore library (spec §4.8.3).
         */
        WriteTargetAddress: string;
        /**
         * @description Capability authorising the write (spec §3.5.9). Required when the
         *     identity does not own the target; omitted otherwise.
         */
        WriteCapabilityId: string;
        /** @enum {string} */
        ReplicationMode: "full" | "selective" | "index_only";
        /** @description Node-local replication policy (spec §4.6.1). */
        ReplicationPolicy: {
            mode: components["schemas"]["ReplicationMode"];
            /** @description The `selective` filter; null in other modes. */
            filter: components["schemas"]["FilterSpec"] | null;
            /** @description Whether replication is running (spec §5.4.4). */
            connected: boolean;
        };
        /**
         * @description Recursive predicate (spec §3.5.7). v1.1 node types are `match`,
         *     `any_of`, `range`, `and`, `or`, and `not`. The schema admits any
         *     `type` so a node can report filters from newer peers; a filter
         *     holding a type the node does not recognise matches nothing.
         */
        FilterSpec: {
            type: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Who a capability is for (spec §3.5.5): `key` with `key`, or
         *     `key_set` with `keys`. Any other `type` matches no signer.
         */
        GranteeSpec: {
            type: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Capability condition (spec §3.5.8). v1.1 defines `expires_at`
         *     with `at` in Unix milliseconds. Any other `type` never holds.
         */
        ConditionSpec: {
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** @description A capability record and its state (spec §3.5.5). */
        Capability: {
            /** @description Entry hash of the capability record's entry. */
            capability_id: string;
            library_address: string;
            /** @description Public key that signed the capability. */
            issuer: string;
            /** @description The capability the issuer cited, for a delegated grant. */
            via_capability_id?: string | null;
            grantee: components["schemas"]["GranteeSpec"];
            /** @description Action verbs (spec §3.5.6), including any the node does not recognise. */
            actions: string[];
            filter: components["schemas"]["FilterSpec"] | null;
            conditions: components["schemas"]["ConditionSpec"][];
            /** @description The record's `timestamp`. */
            issued_at_ms: number;
            /** @description The earliest `expires_at` condition, if any. */
            expires_at_ms?: number | null;
            /**
             * @description `revoked` when an effective revocation names it, and `inert`
             *     when the capability's own entry is inert (spec §3.5.10). Both
             *     follow verification. `expired` is advisory: it means an
             *     `expires_at` is past by the node's clock, so a write the node
             *     makes now, timestamped now, would fail §3.5.8. Verification
             *     judges expiry by each operation's own timestamp, so entries
             *     already written stay valid.
             * @enum {string}
             */
            status: "active" | "expired" | "revoked" | "inert";
            /** @description Entry hash of the effective revocation, if any. */
            revoked_by?: string | null;
        };
        /** @description One entry of the identity library (spec §4.8.2). */
        MetaLogRecord: {
            entry_hash: string;
            /** @enum {string} */
            op: "PUT" | "DEL";
            /** @description Record type, `library`, `link`, `pin`, or one the node does not recognise. */
            type: string;
            key: string;
            /** @description The operation value as stored. */
            record: {
                [key: string]: unknown;
            };
            clock_time: number;
            timestamp_ms: number;
            /** @description Whether this is the current record for its `(type, key)`. */
            is_current: boolean;
        };
        MetaLogPage: {
            /** @description The identity library address (spec §3.6.2). */
            address: string;
            heads: string[];
            items: components["schemas"]["MetaLogRecord"][];
            total: number;
        };
        /**
         * @description Normalized replication progress. Same shape as the
         *     `library:replicate-progress` WebSocket event payload.
         */
        ReplicationStatus: {
            /** @description Count of entries synced so far. */
            progress: number;
            /** @description Total entries expected in the current sync window. */
            total: number;
        };
        /** @description Profile-only projection of a library. */
        About: {
            library_address: string;
            name?: string | null;
            bio?: string | null;
            location?: string | null;
            avatar?: string | null;
        };
        ListenCount: {
            track_id: string;
            count: number;
            timestamps_ms?: number[];
        };
        Peer: {
            peer_id: string;
            multiaddrs: string[];
            /** @description Library addresses advertised by this peer. */
            library_addresses?: string[];
            /** @description Unix milliseconds when the peer connection was established. */
            connected_at_ms?: number;
        };
        /**
         * @description Node info. `peer_id` is the only guaranteed field; everything
         *     else is optional and may be omitted when unavailable.
         */
        Settings: {
            /** @description libp2p peer id of the node. */
            peer_id: string;
            /** @description libp2p multiaddrs the node is listening on. */
            addresses?: string[];
            /** @description record-node build version. */
            version?: string;
            /**
             * @description The node's network mode (spec §5.6). In `masked` mode
             *     `addresses` is empty: the node listens on nothing.
             * @enum {string}
             */
            network_mode?: "public" | "masked" | "relayed";
            /**
             * @description Bandwidth counters. Values are decimal-encoded strings
             *     because the underlying counters are unbounded integers.
             */
            bandwidth?: {
                total_in_bytes?: string;
                total_out_bytes?: string;
                rate_in_bytes_per_sec?: string;
                rate_out_bytes_per_sec?: string;
            };
            storage?: {
                used_bytes?: number;
                max_bytes?: number;
                object_count?: number;
            };
        };
        Identity: {
            /** @description Compressed secp256k1 public key, 66 lowercase hex characters (spec §3.1). */
            public_key: string;
            /** @description Address of the identity library (spec §3.6.2). */
            meta_log_address: string;
            /**
             * @description The identity's default own recordstore library: its only
             *     active one, or else the one with discriminator `record`,
             *     record-node's v1.0 own library (spec §3.6.1).
             */
            own_library_address: string;
        };
        /**
         * @description Hex-encoded libp2p marshaled keypair. Both fields include the
         *     key-type header so `private_key` round-trips through
         *     `POST /identity/import`.
         */
        IdentityExport: {
            public_key: string;
            private_key: string;
        };
        ImportAck: {
            /**
             * Format: uuid
             * @description Identifier for tracking progress via `import:*` WebSocket events.
             */
            import_id: string;
            /** @description Number of files accepted (multipart only). */
            file_count?: number;
        };
        /**
         * @description Canonical shape per protocol spec §2.4.2. `(extractor, id)` MUST
         *     uniquely identify an external source pointer. Streaming `url`
         *     fields MUST NOT be persisted (spec §2.4.2).
         */
        ResolverEntry: {
            extractor: string;
            id: string;
            fulltitle?: string;
            thumbnail?: string;
            artist?: string;
            alt_title?: string;
            upload_date?: string;
            webpage_url?: string;
            duration?: number;
        };
    };
    responses: {
        /** @description Request validation failed. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The bearer token is missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Caller is not authorized to perform this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation conflicts with existing state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unhandled exception. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The resolver could not resolve a URL it accepted as input. The
         *     error carries `RESOLVER_FAILED` and `resolver_code`.
         */
        ResolverFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Pagination offset. Default 0. */
        Offset: number;
        /** @description Maximum results per page. Default 100, max 500. */
        Limit: number;
        /** @description Full library address, e.g. `/record/<manifest-cid>/<name>`. */
        LibraryAddress: string;
        /**
         * @description Target library of the write. Optional only when the identity has
         *     exactly one active own recordstore library (spec §4.8.3).
         */
        WriteTarget: string;
        /**
         * @description Capability authorising the write (spec §3.5.9). Required when the
         *     identity does not own the target; omitted otherwise.
         */
        WriteCapability: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
